# Numpy Array

In [1]:
# import the library
import numpy as np

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [6]:
lst1=[1,2,3,4,5]
lst2=[6,7,8,9,0]
lst3=[3,6,8,1,7]

arr1=np.array([lst1,lst2,lst3])

In [7]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 6, 8, 1, 7]])

In [8]:
arr1.shape

(3, 5)

In [9]:
# Indexing

arr[3]

4

In [10]:
arr[1:3]

array([2, 3])

In [11]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 6, 8, 1, 7]])

In [12]:
arr1[:,1]

array([2, 7, 6])

In [13]:
arr1[1:,1:3]

array([[7, 8],
       [6, 8]])

In [14]:
arr1[1:,3:]

array([[9, 0],
       [1, 7]])

In [15]:
# EDA

arr

array([1, 2, 3, 4])

In [16]:
arr<2

array([ True, False, False, False])

In [17]:
arr[arr<2]

array([1])

In [18]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 3, 6],
       [8, 1, 7]])

In [22]:
arr * arr

array([ 1,  4,  9, 16])

In [23]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [36, 49, 64, 81,  0],
       [ 9, 36, 64,  1, 49]])